name: Build on Linux

on: [push, pull_request]

jobs:
  build-linux-i386:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build linux-i386
      run: cd src && git submodule init && git submodule update && sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install -y aptitude && sudo aptitude install -y libopenal-dev:i386 g++-multilib gcc-multilib libpng-dev:i386 libjpeg-dev:i386 libfreetype6-dev:i386 libfontconfig1-dev:i386 libcurl4-gnutls-dev:i386 libsdl2-dev:i386 zlib1g-dev:i386 libbz2-dev:i386 libedit-dev:i386 && cd src/ && ./waf configure -T release && ./waf build

    - name: Zip up game directory
      run: |
        cd ..
        zip -9 -r game-release.zip game/
        echo "Game directory zipped to game-release.zip"

    - name: Create GitHub Release
      if: github.event_name != 'pull_request'
      uses: actions/create-release@v1
      id: create_release
      with:
        tag_name: ${{ github.sha }}
        release_name: AutoRelease ${{ github.sha }}
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload game artifact
      if: github.event_name != 'pull_request'
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./game-release.zip
        asset_name: game-release.zip
        asset_content_type: application/zip
